### ISSUE TITLE
Support to have generated file as json instead of js/ts

### ISSUE THREAD

**Issue by tarangkhandelwal** [kreuzerk/svg-to-ts#111]
Hi,
We have a use case where we don't want to have output as a Javascript object in js/ts file but instead a json file. 
We are primarily avoiding .ts file so that doesn't get bundled as part of main bundle. We will dynamically import the json file to add icons to icon registry.

Is providing output file to be a json already supported or something that seems like a valid requirement?

**Comment by kreuzerk** [comment]
HI @tarangkhandelwal 

Thx a lot for bringing this up. Converting SVG to JSON is currently not implemented. As the name indicates, the goal of this project is to transform the SVG icons into TypeScript. Converting to JSON doesn't really fit into this project. Maybe it could be a fork of this repository or in a new project.

Kind regards
