### ISSUE TITLE
Script adds additional space in filename.

### ISSUE THREAD

**Issue by fstodulski** [kreuzerk/svg-to-ts#112]
Script adds additional space in filename between prefix and icon's filename.
![image](https://user-images.githubusercontent.com/14015728/111615432-0834c700-87e1-11eb-9a2f-fb7cff72bc57.png)

Config:
<pre>
<code>
"svg-to-ts": {
    "generateType": "true",
    "delimiter": "KEBAB",
    "conversionType": "files",
    "iconsFolderName": "svg",
    "prefix": "app",
    "srcFiles": [
      "./libs/tetrisly/src/assets/svg/**/*.svg"
    ],
    "outputDirectory": "./libs/tetrisly/src/lib/icons/svg-compiled",
    "svgoConfig": {
      "plugins": [
        {
          "removeDimensions": true,
          "cleanupAttrs": true
        }
      ]
    }
  }
  </code>
</pre>

**Comment by kreuzerk** [comment]
Hi, @fstodulski thanks for reporting this issue. 

I tried to reproduce this issue with your configuration in a new starter project. I also tried to reproduce it in svg-to-ts itself. Unfortunately, I couldn't reproduce it. Also svg-to-ts is used across multiple organizations and we never encountered this issue. I guess there must be something wrong with your raw svg-icons or something else. Do you have a reproduction project?
