### ISSUE TITLE
SyntaxError: ']' expected

### ISSUE THREAD

**Issue by tomsoftwarealliance** [kreuzerk/svg-to-ts#114]
I was using[ svg-icon-library-starter](https://github.com/kreuzerk/svg-icon-library-starter), following the instructions and using these configurations:

**.svg-to-tsrc** 
```
{
    "conversionType": "files",
    "srcFiles": [
      "./svg-icons/**/*.svg"
    ],
    "outputDirectory": "./dist/icons",
    "interfaceName": "SalIcon",
    "typeName": "salIcon",
    "prefix": "salIcon",
    "generateType": true,
    "exportCompleteIconSet": true,
    "optimizeForLazyLoading": true,
    "modelFileName": "salIcons.model",
    "compileSources": true
}

```

I ran `npm run serve` which produced this error

```
==========================================================
� Hi I am svg-to-ts - let's build an awesome icon library
==========================================================
svg-to-ts: ℹ️ We are using the conversiontype "files"
svg-to-ts: √ Deleting the output folder
svg-to-ts: √ Processing SVG files
svg-to-ts: √ Generate SVG constants
svg-to-ts: × Export complete icon set
svg-to-ts: SyntaxError: ']' expected. (2:33)
  1 | /* � this file was generated by svg-to-ts*/
> 2 | export const completeIconSet = [
    |                                 ^
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sal-icons@1.0.0 transform-icons: `svg-to-ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sal-icons@1.0.0 transform-icons script.
```

I've not altered anything from the starter except the recommended REPLACE_ME text. This seems to be an issue with this package.

**Comment by atbostudio** [comment]
do you have any svg files in the given ("./svg-icons/") folder? 
i had this error when the the path wasn't correct or the folder was empty.
 
maybe re-run npm install after deleting node_modules folder and package.lock.json.
if you are using windows try to adjust the path maybe.

here is also a running configuration, which worked for me, you might try (you may change the paths for your needs):
```
"svg-to-ts": {
    "conversionType": "files",
    "srcFiles": [
      "./projects/test-icons/**/*.svg"
    ],
    "outputDirectory": "./projects/test-icons/icons/lib/",
    "interfaceName": "TestIcon",
    "typeName": "testIcon",
    "prefix": "test",
    "svgoConfig": {
      "plugins": [
        {
          "cleanupAttrs": true
        }
      ]
    },
    "fileName": "test-icon.model",
    "additionalModelFile": "./projects/icons/src/lib",
    "compileSources": true
  },
```

before running `ng serve` you could try `npm run transform-icons` which only triggers `svg-to-ts`

**Comment by ERRORthenBSOD** [comment]
Hi! I have the same issue with step "Export complete icon set", when i try to build icons in docker container! Eveything is fine outside docker

**Comment by kreuzerk** [comment]
Can you retry with the latest version?

**Comment by kreuzerk** [comment]
Hi @tomsoftwarealliance I will close this because I think this should be fixed with the latest version. Let me know if not and I am happy to reopen the issue.
