### ISSUE TITLE
Export all icons from icons.ts (conversionType==='constants')

### ISSUE THREAD

**Issue by Guzel738** [kreuzerk/svg-to-ts#132]
**Environment**

- Angular 12;
- svg-to-ts 6.0.2.

**Problem**

In the second approach to converse types (conversionType==='constants'), generated file icons.ts doesn`t contain export of all icons. So everytime we add new icon in method registerIcons() and we need to add this icon to the import list.

It should be better to have singe export with all constants as : export const all = [icon1, icon2, ...].

Would it be possible to add this functionality?

**Comment by kreuzerk** [comment]
Yes, that would make perfect sense. I will try to add this feature once I find the time.

**Comment by kreuzerk** [comment]
Hi @Guzel738 with version 8.3 a complete icon set gets generated by default when using the constant conversion type

**Comment by Guzel738** [comment]
Thank you!
