### ISSUE TITLE
Adding svgoConfig file path as a command line argument

### ISSUE THREAD

**Issue by josealeixopc** [kreuzerk/svg-to-ts#136]
Hello. First of all, thank you so much for maintaining this tool!

I've recently updated `svg-to-ts` to 7.1.0 and noticed that some of my icons were not scaling properly. I figured it had to do with SVGO [setting `removeViewBox` as a default plugin](https://github.com/svg/svgo/pull/1461). I wish to use my own SVGO config to disable this behavior.

I have added a `svgo.config.js` file to the root of my project and successfully gotten the desired behavior. However, I would like to keep the root folder as little "polluted" as possible. I was wondering if on the most recent version (`7.1.0`) there is a way of providing the path to the `svgo.config.js` file in the command line. If not, could you provide an example of a "inline configuration object" for the SVGO config?

Cheers!

**Comment by kreuzerk** [comment]
HI @josealeixopc thx a lot for the question. Currently, we don't support custom paths for svgo configs. However, you can always configure your `svgo` inline in your `svg-to-ts` config. See an example in the [README](https://github.com/kreuzerk/svg-to-ts) where we configure svgo inside the `svg-to-ts` object in the `package.json`

**Comment by kreuzerk** [comment]
```
{
  "name": "my-icon-library",
  "version": "3.4.0",
  "scripts": {
    "generate-icons": "svg-to-ts"
  },
  "svg-to-ts": {
    "conversionType": "constants",
    "srcFiles": ["./projects/dinosaur-icons/icons/**/*.svg"],
    "outputDirectory": "./projects/dinosaur-icons/icons",
    "interfaceName": "DinosaurIcon",
    "typeName": "dinosaurIcon",
    "prefix": "dinosaurIcon",
    "svgoConfig": {
      "plugins": ["cleanupAttrs"]
    },
    "fileName": "dinosaur-icon.model",
    "additionalModelFile": "./projects/dinosaur-icons/src/lib",
    "compileSources": true
  }
}
```

**Comment by josealeixopc** [comment]
Thanks @kreuzerk ! Passing the config using the `svgoConifg` field worked :)

**Comment by kreuzerk** [comment]
@josealeixopc 👍 Glad to hear that it worked
