### ISSUE TITLE
Generate types for "conversionType": "object",

### ISSUE THREAD

**Issue by cakeinpanic** [kreuzerk/svg-to-ts#137]
Hi!
I'd like to have an option to generate types even if I'm converting SVGs to one object

Types can be used like that:
```typescript
export type MyIconsType = 'heart-icon' | 'home-icon'

export const MyIcons: { [key in MyIconsType]: string }= {
 'heart-icon':   '<svg></svg>',
 'home-icon':    '<svg></svg>'
}


```

**Comment by kreuzerk** [comment]
Hi @cakeinpanic. Thx a lot for the feature request. This request makes perfect sense. I can take a look at this once I find the time. Of course, if you want, you can also create a PR ;).

**Comment by cakeinpanic** [comment]
@kreuzerk hi, I just opened a PR :)
