### ISSUE TITLE
It will fail if there's a `.DS_Store` file in the folder 

### ISSUE THREAD

**Issue by yagoferrer** [kreuzerk/svg-to-ts#14]
It will fail if there's a `.DS_Store` file in the folder. It should ignore "hidden" files.

Error:
```
svg-to-ts: Something went wrong Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char:
```

**Comment by Palapapaa** [comment]
Hi !

Maybe we should just check that we only work on `.svg` files.

**Comment by kreuzerk** [comment]
Yes. that would be a good solution.
