### ISSUE TITLE
svg-to-ts-object generates consts

### ISSUE THREAD

**Issue by eckmLJE** [kreuzerk/svg-to-ts#155]
Hello, I had previously and successfully configured for v7 and am now trying to configure with v8. My understanding is I should run `npx svg-to-ts svg-to-ts-object` and this replaces `conversionType: "object"` in the config. However, when I run `npx svg-to-ts svg-to-ts-object`, svg-to-ts generates consts and not an object. What am I doing wrong?

```json
  "scripts": {
    "generate-icons": "npx svg-to-ts svg-to-ts-object"
  },
  "svg-to-ts": {
    "srcFiles": [
      "./src/icons/**/*.svg"
    ],
    "outputDirectory": "./src/icons",
    "objectName": "iconSvgStrings",
    "interfaceName": "IconSvgStringInterface",
    "typeName": "IconSvgStringType",
    "svgoConfig": {
      "plugins": [
        "cleanupAttrs"
      ]
    },
    "fileName": "index"
  },
```
<img width="852" alt="Screen Shot 2022-02-15 at 9 52 06 AM" src="https://user-images.githubusercontent.com/31972879/154086662-77bc2f01-08ab-4a12-b61e-9bc920db37fe.png">

**Comment by kreuzerk** [comment]
Hi @eckmLJE your script section should look like this.

````
  "scripts": {
    "generate-icons": "npx svg-to-ts svg-to-ts-object"
  },

**Comment by eckmLJE** [comment]
This is what I get when I run this

<img width="456" alt="Screen Shot 2022-02-15 at 9 59 00 AM" src="https://user-images.githubusercontent.com/31972879/154088020-350a9dbf-2467-459d-b183-2cfd7eb971f6.png">

<img width="874" alt="Screen Shot 2022-02-15 at 9 58 04 AM" src="https://user-images.githubusercontent.com/31972879/154087938-c8eebe95-a443-445e-9f8e-dc06ed5b366f.png">

**Comment by kreuzerk** [comment]
Sorry, you are right your command was correct. I overlooked the `npx` call. I will try to take a look

**Comment by eckmLJE** [comment]
Great, thank you!

**Comment by eckmLJE** [comment]
This appears to have done the trick. What is the -p flag?

**Comment by eckmLJE** [comment]
👍🏻 Sure thing, thanks again for the quick response.

**Comment by kreuzerk** [comment]
Thx for reporting the issue 👍
