### ISSUE TITLE
Support to SVG React Component

### ISSUE THREAD

**Issue by conradopsa** [kreuzerk/svg-to-ts#159]
Hello! This library is so fantastic and very useful for a React project that I developing.

Unfortunately, that lib is not 100% compatible with React.
When SVG are generated, svg information is stored as String.
But React don't recognize a String as SVG, it understand only if SVG is a React Component.

So in the example below, generated files is not useful :(
![image](https://user-images.githubusercontent.com/25545994/158254667-9dbcbe30-89d3-4d54-bc6e-e8acb81195b0.png)

But... if i remove quotation marks of all string values and save as tsx file problem is solved and React understand as React Component! :)
![image](https://user-images.githubusercontent.com/25545994/158254828-65385299-dca6-451c-ab00-bdb3e4232fe7.png)

Please, if possible to add a new feature to indicate a React Generator I'll be very thankful!

**Comment by kreuzerk** [comment]
Hi @conradopsa thx a lot for the issue. Great to hear that you use it with React. I am not too familiar with React. But I am curious how you use the icons. The goal of the project is to transform SVG icons into valid TypeScript. That's the reason why we store the SVGs as string. If I am right, removing the quotes would resolve in invalid TypeScript code.

**Comment by Bilal-io** [comment]
@kreuzerk the files can be exported as `.tsx` so that eslint understands it's "JSX". Another thing, `class="..."` has to be changes to `className="..."`
I cannot think of any other attributes that an SVG has which would be considered invalid JSX.

**Comment by kreuzerk** [comment]
@Bilal-io thx a lot for the explenation. I now understood it. Will try to take a look at this once I find time.

**Comment by kreuzerk** [comment]
Hi @Bilal-io @conradopsa I just released v8.5.0 which introduces a `tsx` flag that you can use to generate valid TSX files. With this change you should now be able to use the generated output directly as a react component.

**Comment by manandkumaar** [comment]
Hi @kreuzerk , @conradopsa , @Bilal-io ,

I am trying to implement tree-shakable icons in my react app. 

Is there a sample app for reactjs to refer?.
Thanks.

**Comment by kreuzerk** [comment]
Hi there, no, unfortunately, afaik, there's no demo app. Initially, this project was made for Angular. We then later added react support. I am not a react dev, but from my point of view, the concept of a tree-shakable library should be similar.

**Comment by manandkumaar** [comment]
Thank you @kreuzerk. Let me try to integrate with CRA and let you know if any help is needed.
