### ISSUE TITLE
 ENOENT  not found: svg-to-ts

### ISSUE THREAD

**Issue by imike57** [kreuzerk/svg-to-ts#183]
Hello,

Does someone make it work with pnpm ? 

If I set a script in my package.json as specified in the documentation

```
{
    "scripts": {
        "generate-icons": "svg-to-ts"
    }
}
```

I got 
` ENOENT  not found: svg-to-ts`
 

pnpm --version
6.24.4
node --version
v16.13.1

**Comment by kreuzerk** [comment]
The latest version of `svg-to-ts` doesn't export a binary named `svg-to-ts`. Try to call either `svg-to-ts-object`, `svg-to-ts-constants` or `svg-to-ts-files`. Checkout the [Readme](https://github.com/kreuzerk/svg-to-ts#binaries) to find out more about those options.

**Comment by kreuzerk** [comment]
@imike57 I just tried it out locally with `pnpm` and it works perfectly if I use one of the binaries described above. Let me know if it works for you.

**Comment by imike57** [comment]
@kreuzerk thank's. It works.

**Comment by kreuzerk** [comment]
@imike57 👍
