### ISSUE TITLE
after running npm i svg-to-ts --> error svg-to-ts command not found

### ISSUE THREAD

**Issue by roman-gyver** [kreuzerk/svg-to-ts#184]
I installed and configured svg-to-ts as was instructed, but i get constantly svg-to-ts command not found.I even tried with npm install svg-to-ts -g and no help.

**Comment by kreuzerk** [comment]
Hi @roman-gyver, thx a lot for this question. I guess you were instructed by an outdated tutorial. We recently renamed the binary to `svg-to-ts-constants`, `svg-to-ts-files`and `svg-to-ts-objects`. There's no longer a `svg-to-ts`command.

Hope that helps, let me know if you need more help.

**Comment by roman-gyver** [comment]
Hi @kreuzerk, thank you for quick answer, `svg-to-ts-constants` worked and was the right one for our needs! Have a great day! :)

**Comment by roman-gyver** [comment]
Hi @kreuzerk, thank you for quick answer, `svg-to-ts-constants` worked and was the right one for our needs! Have a great day! :)

**Comment by kreuzerk** [comment]
👍 happy to hear that it worked.
