### ISSUE TITLE
Cannot run svg-to-ts, executable not found

### ISSUE THREAD

**Issue by samjt** [kreuzerk/svg-to-ts#194]
## Bug or Documentation unclear?
Running `npx svg-to-ts` or `npx svg-to-ts svg-to-ts-files` as mentioned in the documentation results in 

```
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2022-10-31T14_19_30_393Z-debug-0.log
```

[2022-10-31T14_19_30_393Z-debug-0.log](https://github.com/kreuzerk/svg-to-ts/files/9901915/2022-10-31T14_19_30_393Z-debug-0.log)

Using npm installed version has the same problem:

```json
{
  "name": "svgts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "icons": "svg-to-ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "svg-to-ts": "^8.8.1"
  }
}
```

`npm run icons` also results in an error, in a brand new empty project.

I have tested with both `npm` and `npx` as well as `yarn`.
Also tested with svg-to-ts v8.9.0 and v8.8.1 All result in the same error.

## Working Version 
If I explicitly call using the path `node_modules/.bin/svg-to-ts-files` or `npx svg-to-ts-files` it does run
if I explicitly set the binary I want in package.json, it will also run
```json
{
  "name": "svgts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "icons": "svg-to-ts-files",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "svg-to-ts": "^8.8.1"
  }
}
```

node v18.12.0
npm v8.19.2

**Comment by kreuzerk** [comment]
Thx a lot for this question. The latest version of svg-to-ts doesn't export a binary named svg-to-ts. Try to call either svg-to-ts-object, svg-to-ts-constants or svg-to-ts-files. Checkout the [Readme](https://github.com/kreuzerk/svg-to-ts#binaries) to find out more about those options.

**Comment by kreuzerk** [comment]
If you want to run svg-to-ts with npx your command should look like this:
`npx svg-to-ts svg-to-ts-object`

**Comment by kreuzerk** [comment]
Hi there, I took another look at this issue. Can you try and check if the following command works? `npx -p svg-to-ts sv-to-ts-files`?

**Comment by kreuzerk** [comment]
I just updated the `README.md`file. I will close this issue for now, please let me know if this issue still exists.
