### ISSUE TITLE
Icon name using folder as name

### ISSUE THREAD

**Issue by lpzapata** [kreuzerk/svg-to-ts#196]
I was wondering if you can add (if there already isn't a way to do this) where it uses the folder's location as a way to name the component. 
I'm having an issue because my folder structure looks like this, and I would love to keep this nested structure for some other reasons: 
|-Arrow
|----Up.svg
|----Down.svg
|----Left.svg
|----Right.svg
...
|-Chevron
|----Up.svg
|----Down.svg
|----Left.svg
|----Right.svg

**Comment by kreuzerk** [comment]
HI @lpzapata if I understand you correctly you can achieve this behaviour today by using a configuration array. The `.svg-to-ts` config accepts an array. So you could have a configuration for each folder. In the configuration you can then set the prefix which should be used.

**Comment by lpzapata** [comment]
@kreuzerk, that's really cool. Excuse my naivety. How would I be able to make it a dynamic array cause I'm trying to set up to build a variety of icon libraries and I won't always know how many folders there are (nor would I want to add a custom config for each library type.)

**Comment by kreuzerk** [comment]
I think this could be solved by adding some custom logic. So the `svg-to-ts`config can either be a JSON or it can also be a JavaScript file. If you use a JavaScript file you should be able to add your specific logic to this file.

**Comment by kreuzerk** [comment]
Will close this ticket for now, please let me know if the proposed solution worked for you.
