### ISSUE TITLE
update to svgo version 3.x

### ISSUE THREAD

**Issue by mkurcius** [kreuzerk/svg-to-ts#207]
Currently when installing `svg-to-go` npm is reporting `stable` lib is deprecated:

```
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
```

`npm ls stable` shows it is used by `svgo@2.8.0`
```
└─┬ svg-to-ts@9.0.0
  └─┬ svgo@2.8.0
    └── stable@0.1.8
```

in svgo@3 `stable` is not used anymore

 `npm show svgo dependencies`
```json
{
  '@trysound/sax': '0.2.0',
  commander: '^7.2.0',
  'css-select': '^5.1.0',
  'css-tree': '^2.2.1',
  csso: '^5.0.5',
  picocolors: '^1.0.0'
}
```

Therefor if `svg-to-go` will migrate to `svgo@3` deprecation warning will be fix :)

**Comment by kreuzerk** [comment]
Hi @mkurcius thx a lot for reporting this issue and for the very nice analysis. We just released version 10 of svg-to-ts which brings svgo 3. I will close this issue for now. Let me know if you still encounter issues.
