### ISSUE TITLE
How to customize size and apply primary color

### ISSUE THREAD

**Issue by patolax** [kreuzerk/svg-to-ts#215]
How do we change the color and size of the icons?

None of these work.
style="color: brown;"
style="width: 150px; height: 150px"

I am using this in an angular project following instructions in the readme.

**Comment by cit-eriks** [comment]
I also have the same doubt!!!

Angular Project

**Comment by patolax** [comment]
@felipeplets  @kreuzerk is this actively maintained?

**Comment by kreuzerk** [comment]
Yes, but I am not sure if this issue really has to do with this project. I think if you want to colorize the icons you either have to export the icon differently or adjust the svgo config that you pass to svg-to-ts.

**Comment by patolax** [comment]
@kreuzerk I followed your [post  ](https://www.youtube.com/watch?v=s1yrxEJeop4) and tried this code below. As you can see no change to size or color.

<gm-icons style="color: red;width: 110px; height: 101px" name="achilles"></gm-icons>

![image](https://github.com/kreuzerk/svg-to-ts/assets/29444156/a08ebf56-bd35-42a8-ba47-75a49e16fae3)

I cleaned up the size and fill properties from my lib and tried to apply color and size. Still, it did not work. 

It would be really nice if you can provide us proper guidelines as to how to prepare the svgs and how to propagate color and size to them.

Highly appreciate any help.

**Comment by JesseZomer** [comment]
probably has to do with this: https://github.com/kreuzerk/svg-to-ts/issues/218. See the thread mentioned in https://github.com/kreuzerk/svg-to-ts/issues/218#issuecomment-1625247325 about some weird svgo defaults

**Comment by kreuzerk** [comment]
Hi @patolax the reason why the icon from the greek mythology library can not be colored is because each path has a hardcoded color in the icon. To color such icons you have to replace the hardcoded colors with the value of `currentColor`. To do so you can use the following configuration on the `svgoConfig` -> `plugins` inside your `.svg-to-tsrc`.

```javascript
{
  name: 'convertColors',
  params: {
    currentColor: new RegExp(/#(?!FFFFFF).{6}/),
  }
},
```
