### ISSUE TITLE
'svg-to-ts' is not recognized as an internal or external command (Angular 15)

### ISSUE THREAD

**Issue by milosavljevic94** [kreuzerk/svg-to-ts#223]
Hi, I follow instructions from repository but have error : 'svg-to-ts' is not recognized as an internal or external command,
operable program or batch file.
My script object: 
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "generate-icons": "svg-to-ts"
  },

svg-to-ts config object: 
"svg-to-ts": {
    "srcFiles": ["./src/assets/images/Svg/*.svg"],
    "outputDirectory": "./src/assets/images/Svg",
    "interfaceName": "ShopIcon",
    "typeName": "shopIcon",
    "prefix": "app",
    "svgoConfig": {
      "plugins": ["cleanupAttrs"]
    },
    "fileName": "shop-icon.model",
    "compileSources": true
  }
I tried npm run generate-icons command,  but get following error.
Note: on versions about 5-6 it's working, but when upgrade to 8-10 it's not.

**Comment by kreuzerk** [comment]
Hi there, which version of svg-to-ts are you using. The `svg-to-ts` command was reworked into three specific commands. 

- svg-to-ts-object
- svg-to-ts-constants
- svg-to-ts-files

You can find more info in the [README](https://github.com/kreuzerk/svg-to-ts#usage)

**Comment by milosavljevic94** [comment]
Hi, when I was on version 10 of angular, I used` svg-to-ts` version: ^5.0.0 . 
Now when I upgrade angular to 15 I using `svg-to-ts` version: ^10.0.0.

**Comment by kreuzerk** [comment]
Great! As mentioned in the previous comment the `svg-to-ts` command has been reworked into `svg-to-ts-object`, `svg-to-ts-constants` and `svg-to-ts-files`. In version 10 you can use one of those three binaries.

**Comment by kreuzerk** [comment]
Perfect! Happy to hear that it works!
