### ISSUE TITLE
Config option "tsx: true" error: Parameter 'props' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by logancool** [kreuzerk/svg-to-ts#226]
When setting `tsx: true` typescript will error since props passed has no type defined. 

https://github.com/kreuzerk/svg-to-ts/blob/8ff40a1d49c92a08958e1557943f981c95ff2d90/src/lib/generators/code-snippet-generators.ts#L116

**Comment by kreuzerk** [comment]
Hi @logancool thx a lot for reporting this issue. In version 11.0.1 the `props` are now typed in the following way `{[key:string]: any}`.

**Comment by kreuzerk** [comment]
@all-contributors please add @logancool for bug
