### ISSUE TITLE
Expression produces a union type that is too complex to represent.

### ISSUE THREAD

**Issue by imike57** [kreuzerk/svg-to-ts#230]
Hello,

When using `svg-to-ts-constants` with the `exportCompleteIconSet: true` option, if I have a large number of icons, it generates an array that triggers the error message: "Expression produces a union type that is too complex to represent."

However, if I remove some elements from this array to reduce the number, the error no longer occurs. This error is displayed in both Visual Studio Code and the compiler.

I believe I may be encountering the same issue as described here: https://github.com/kreuzerk/svg-to-ts/pull/181. However, I've tested it with versions 8.8.1 and 10.1.0, and there was no difference in the result.

**Comment by kreuzerk** [comment]
Hi @imike57 did you try to use the `generateType` flag? If you set that flag to `false` no types should be generated which should fix your issue. Can you try this and let me know if it works. Thx.
