### ISSUE TITLE
API in command line documentation

### ISSUE THREAD

**Issue by akehir** [kreuzerk/svg-to-ts#28]
https://github.com/kreuzerk/svg-to-ts/blob/1080983542ece92e69f49b778eee6271e29c6e30/src/bin/svg-to-ts.ts#L48

Not just the readme, this also seems to need to be updated to compileSources.

**Comment by kreuzerk** [comment]
@akehir Thank you very much for pointing this out. I just pushed the changes. Everything should be fixed with version 4.0.5. 

Thanks a lot
