### ISSUE TITLE
Allow to customize the barrel file name

### ISSUE THREAD

**Issue by dsebastien** [kreuzerk/svg-to-ts#32]
For scenarios in which we chose not to compile the code it would be nice to be able to chose the barrel file name.

**Comment by felipeplets** [comment]
@dsebastien My understanding is that you would like to be able to set a parameter, let's say `--barrelFileName=myBarrelFile` and instead of the generating the barrel file as `index.ts` if would generate as `myBarrelFile.ts`.
Am I correct?

**Comment by dsebastien** [comment]
Yep, exactly!
