### ISSUE TITLE
Failed svg to ts conversion

### ISSUE THREAD

**Issue by dsebastien** [kreuzerk/svg-to-ts#37]
Hello,

I'm facing a weird issue with svg-to-ts. It seems to work fine for SVG icons coming from material design icons, but with the following file (and others) that I've received from a designer, it seems to fail silently.

Here's the SVG file:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="72px" height="64px" viewBox="0 0 72 64" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 64 (93537) - https://sketch.com -->
    <title>Icons/icon-main-burger-hover</title>
    <desc>Created with Sketch.</desc>
    <g id="Icons/icon-main-burger-hover" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect id="Rectangle-Copy-7" x="0" y="0" width="72" height="64"></rect>
        <rect id="Rectangle" fill="#E30F89" x="26" y="23" width="22" height="2"></rect>
        <rect id="Rectangle-Copy-2" fill="#E30F89" x="26" y="31" width="15" height="2"></rect>
        <rect id="Rectangle-Copy" fill="#E30F89" x="26" y="39" width="18" height="2"></rect>
    </g>
</svg>
```
Once converted into TS, here's what is generated:

```
import { DidowiIcon } from './didowi-icon.model';
export const didowiIconMainBurgerActive: DidowiIcon = {
  name: 'main_burger_active',
  data: `<svg width="72" height="64" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M0 0h72v64H0z"/><path fill="#FFF" d="M26 23h22v2H26zM26 31h15v2H26zM26 39h18v2H26z"/></g></svg>`
};
```

As you can see, the generated TS file's data field does not contain the expected SVG data.

Do you have any idea what could be wrong? I've tried removing the comment on top of the SVG, but to no avail.

BTW here's the config of svg-to-ts:

```
"svg-to-ts": {
    "srcFiles": [
      "./libs/web-icons/icons/**/*.svg"
    ],
    "outputDirectory": "./libs/web-icons/src/lib",
    "interfaceName": "DidowiIcon",
    "typeName": "DidowiIconName",
    "prefix": "didowiIcon",
    "optimizeForLazyLoading": true,
    "modelFileName": "didowi-icon.model",
    "additionalModelFile": "./libs/web-icons/src/lib",
    "iconsFolderName": "generated",
    "delimiter": "SNAKE",
    "svgoConfig": {
      "plugins": [
        {
          "cleanupAttrs": true
        }
      ]
    },
    "compileSources": false
  },
```

**Comment by kreuzerk** [comment]
Hi @dsebastien thanks for the great description and the reproduction steps. I created a local project to reproduce your issue. For me everything worked fine with the default `svgoConfig` of `svg-to-ts`. The cleanupAttrs cleans removes the color from your svg icon.

I used the following config which worked:

````
"svg-to-ts": {
    "srcFiles": [
      "./libs/web-icons/icons/**/*.svg"
    ],
    "outputDirectory": "./libs/web-icons/src/lib",
    "interfaceName": "DidowiIcon",
    "typeName": "DidowiIconName",
    "prefix": "didowiIcon",
    "optimizeForLazyLoading": true,
    "modelFileName": "didowi-icon.model",
    "additionalModelFile": "./libs/web-icons/src/lib",
    "iconsFolderName": "generated",
    "delimiter": "SNAKE",
    "compileSources": false
  },
````
When I copied the data from the generated svg and opened it in a browser I got like three pink stripes under each other.

**Comment by kreuzerk** [comment]
Please let me know if this works for you.

**Comment by dsebastien** [comment]
Hello @kreuzerk 

Indeed, you're right! I've verified and indeed, the SVG data is correct, our issue must be elsewhere; might be a CSS issue after all.

I wrongly assumed there was a conversion issue because I didn't find the <rect> elements of the SVG, but I suppose it is due to the compression that is done during conversion.

Sorry for the waste of time, and thanks for looking into this (and for creating this super useful tool! :p)

**Comment by dsebastien** [comment]
It seems that my issue is caused by the fact that the icons I'm now converting have a fill color (white in the example above), while the ones I was using earlier from Angular material had fill="none":

I could work around it using svgo plugins, but I still have an issue with the shape itself. Apparently the icon above's rectangle goes out of the bounds of the svg visible space.

By default I set the svg element to be 24x24px, but the rectangle is bigger than that.

Oh my this is complicated.... :D
