### ISSUE TITLE
Add support for object output

### ISSUE THREAD

**Issue by NetanelBasal** [kreuzerk/svg-to-ts#39]
Hey, great library!

I'm about to release a new `<svg-icon>` library where I recommend and show how to use this library.

In my library, we expect to get an object where the `key` is the icon name, and the value is the `content`:

```ts
{
  settings: 'svg...'
}
```

Currently, I expose a function helper that'll make it work with your library:
```ts
import * as icons from '../assets/svg/my-icons.model';

SvgIconsModule.forRoot({
  icons: fromSvgProps(icons)
});
```

Do you think you can add this option as a built-in feature?

**Comment by kreuzerk** [comment]
Hi @NetanelBasal 

Thx a lot. Glad to hear that you like the library and that you want to include it in an article. Yes, we could add this feature. But I am not sure if providing the icons as an object has benefits.

I think that delivering the icons as an object makes them not tree shakable. Currently, we deliver the icons either as single`consts` so that they are tree shakable or even as single files, so that they are tree shakable and can additionally be split to lazy loaded feature modules.

But maybe there's a good reason to do so. Theoretically we could provide all three approaches, object, const and single file. What do you see as benefit of having them as object props instead of individual `consts`?

**Comment by NetanelBasal** [comment]
In real life, most of the applications use a library where you register the icons and use them in the component. The registry expects an object where the key is the icon name, and the value is the SVG content. Let's take my library as an example:

```ts
import { SvgIconsModule, fromSvgProps } from '@ngneat/icons';

import * as icons from '../assets/svg/my-icons.model';

@NgModule({
  imports: [
    SvgIconsModule.forRoot({
      icons: fromSvgProps(icons)
    })
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

And now we can use the icons:

```html
<svg-icon key="settings"></svg-icon>
<svg-icon key="home"></svg-icon>
```

In these cases, there is no benefit of using `constants` because we need an `object`. To support your library, I made the `fromSvgProps` util:

```ts
export function fromSvgProps(propsMap: { [key: string]: { name: string; data: string } }) {
  const map = {};

  for (const { name, data } of Object.values(icons)) {
    map[name] = data;
  }

  return map;
}
```

We can change the API to something like:

```ts
import { location, settings } from '...';

SvgIconsModule.forRoot({
  icons: [location, settings]
})
```

But imagine a big application with hundreds of icons. You'll need to maintain it, and your file will be huge.

**Comment by NetanelBasal** [comment]
If you find it unsuitable for your library, let me know, and I'll create a dedicated library for this :)

**Comment by kreuzerk** [comment]
No, after your explanation I think it makes sense - with this, we could support all scenarios - object, const and multiple files.

**Comment by kreuzerk** [comment]
I will start to work on this soon - hope that I can find time and deliver it asap.

**Comment by NetanelBasal** [comment]
Great! Thanks. In the meantime, when I'll publish it next week, I will instruct to use the `fromSvgProps` helper function.

**Comment by kreuzerk** [comment]
I have implemented a first version that is now able to convert icon to object, constants and files. I just want to quickly check if my current implementation meets your requirement and ensure that I understood you correctly. 

So if we would convert a folder with the following icons:

- expressionLess.svg
- full.svg
- laughing.svg

we would end up with the following file. ``ìcon.ts```

````
export const awesomeIcons = {
  expressionLess:'<svg xmlns="ht....',
  full: '<svg xmlns= ....',
  laughing: '<svg xmlns="http://www....'
};
````

When converting to an object I thought to give the consumer the following options:
|       | type                    | default                                  | output the version number                                                    |
| --------------- | ----------------------- | ---------------------------------------- | ---------------------------------------------------------------------------- |
| fileName        | stirng                  | my-icons                                 | file name of the generated file                                              |
| delimiter       | CAMEL, KEBAP, SNAKE     | SNAKE                                    | delimiter which is used to generate the types and name properties            |
| svgoConfig      | string or config object | check help command - to large to display | a path to your svgoConfiguration JSON file or an inline configuration object |
| srcFiles        | string                  | "/\*.svg"                                | input files matching the given filename pattern                              |
| outputDirectory | string                  | "./dist"                                 | name of the output directory                                                 |

**Comment by NetanelBasal** [comment]
Yes, that's great. I'd also add an option to export it as `default`.

`export default { ... }`

**Comment by NetanelBasal** [comment]
I also think the default delimiter should be camelCase. This is the standard.

**Comment by NetanelBasal** [comment]
Thanks for the quick collaboration! I'll update my library.

**Comment by kreuzerk** [comment]
Awesome, let me know if everything worked

**Comment by NetanelBasal** [comment]
Works great.

**Comment by kreuzerk** [comment]
Epic glad to hear - let me know once your blog post is out. If you want we can also link to it from our README.

**Comment by NetanelBasal** [comment]
I added in the README a recommended flow with your library.

**Comment by kreuzerk** [comment]
Awesome thx.
