### ISSUE TITLE
[Feature request] Union type from array

### ISSUE THREAD

**Issue by Jakob-em** [kreuzerk/svg-to-ts#44]
What do you think about adding the possibility to generate the union type definition like this:

```
const icons = ['icon-1', 'icon-2', 'icon-3'] as const;
type Icon = typeof icons[number];
```

This would allow the use of the array to iterate over the available icons for a showcase page for example.
I would be happy to implement this feature.

**Comment by kreuzerk** [comment]
Hi @Jakob-em 

Thanks a lot for the feature request. We already allow you to generate an Object of the types which you can use to iterate through. To generate this object you need to set the `generateTypeObject` flag to `true`.

The output will be something like this:

`
export type myIcons = 'expression_less' | 'full' | 'laughing' | 'smiling_face';

export const myIcons = {
  expression_less: 'expression_less' as myIcons,
  full: 'full' as myIcons,
  laughing: 'laughing' as myIcons,
  smiling_face: 'smiling_face' as myIcons
};

export interface MyIcon {
  name: myIcons;
  data: string;
}`

**Comment by Jakob-em** [comment]
Hi @kreuzerk,
Thanks for your quick answer. I know that the generation of a union type is currently possible, but the problem with union types is that you can not iterate over the possbile values. To solve this issue and allow for iteration over all icons I suggested to change the generation of the union type to be created via an immutable array. This would allow for both type safety, but also iterating the possible icons

**Comment by kreuzerk** [comment]
Hi @Jakob-em. Yes, but you can iterate over the generated object.

````
export const myIcons = {
  expression_less: 'expression_less' as myIcons,
  full: 'full' as myIcons,
  laughing: 'laughing' as myIcons,
  smiling_face: 'smiling_face' as myIcons
};
````

**Comment by Jakob-em** [comment]
Ah yes your totally right, but this wouldn't work when using conversionType 'files' right? (Thats what i tried to use)

**Comment by kreuzerk** [comment]
It also works for converstionType files.

**Comment by kreuzerk** [comment]
Let me know if there are issues or if you need help

**Comment by Jakob-em** [comment]
Now i get it. Yes this should work. Thanks for the quick help 👍

**Comment by kreuzerk** [comment]
No worries. Glad to hear that it works.
