### ISSUE TITLE
 A conversionType is required, please specify one by passing it via --conversionType

### ISSUE THREAD

**Issue by pyrrhicman** [kreuzerk/svg-to-ts#50]
```
svg-to-ts:  ℹ️ Configuration found under: /Users/ericaskari/Desktop/WEARE/lo-hi/lo-hi-frontend/package.json
svg-to-ts:  A conversionType is required, please specify one by passing it via --conversionType. 
    Valid conversion types are (object, constants or files)
```
It gives me this error although i used `svg-to-ts --conversionType constants` whatever I do I get the same message.

**Comment by kreuzerk** [comment]
Hi @pyrrhicman from the error message it seems like you added a `svg-to-ts` config object in your `package.json`. In this case this config object wins over the command line argument. Can you try to add `"conversionType": "constants"` to your config object in your `package.json`?
