### ISSUE TITLE
svg with masks and clip-paths get broken

### ISSUE THREAD

**Issue by Trigonometric** [kreuzerk/svg-to-ts#51]
If i try to compile svg containing masks or clip-paths, I get broken icons, which look different from the icons before compilation. I have tried all plugins in all values (true/false) with no effect.

**Comment by Trigonometric** [comment]
The problem was in svgo config. By default all ids (of masks and clip-paths) are compiled the same ("a") through the document, so they get confused to each other. All you have to do is to provide config properly `{"cleanupIDs": false}` into the plugins array. It is important that all elements in that array must be separate OBJECTS like `{"cleanupAttrs": true}, {"cleanupIDs": false}`

**Comment by kreuzerk** [comment]
👍  @Trigonometric thanks for bringing this up and explaining the solution.
