### ISSUE TITLE
TypeName in own config object in package not working

### ISSUE THREAD

**Issue by TitoMoi** [kreuzerk/svg-to-ts#54]
[](url)
<img width="1156" alt="Captura de pantalla 2020-08-25 a las 12 24 04" src="https://user-images.githubusercontent.com/43403697/91163809-717eac80-e6ce-11ea-96de-5a8e6cba1212.png">

TypeName is not working, the additionalModelFile is exported correctly but the compiled model name is of type "string"

But, in command line works perfectly.

We had to switch to own config object in package because console in windows don't likes wildcards, only wildcards inside double coma( "../*.svg") so, execute svg-to-ts with all params in script sections works in Mac but not in Windows, so we had to switch to this object, but is not working the TypeName

**Comment by kreuzerk** [comment]
Hi @TitoMoi - Thanks for reporting this. I investigated a bit in this issue and I think you are missing the ``generateType: true`` in your config. 

If I take your config and add the ``generateType: true`` option I get the following model.d.ts file.

```
export declare type IconType = 'expressionLess' | 'full' | 'laughing' | 'smilingFace';
export interface IconInterface {
    name: IconType;
    data: string;
}
```

**Comment by kreuzerk** [comment]
does this fix the issue?

**Comment by TitoMoi** [comment]
Hi @kreuzerk,

I've added the `generateType: true` and works perfectly, the model in the output build is correct and the model in the `additionalModelOutputPath` is correct, the difference I see is that in command line is not necessary to specify the `generateType`prop, that caused me confusion, this is my command line version:

svg-to-ts -s \"projects/merca-icons/svgs/*.svg\" -c files -o projects/merca-icons/svgs -d CAMEL -i IconInterface -t IconType -p \"\"  --modelFileName merca-icon.model --additionalModelOutputPath projects/merca-icons/src/lib/icon --compileSources true

*the scaping \" double comma is for windows users their command line doesn't like the globs so must be wrapped in double comma and package doesn't like double comma inside command so must be escaped.

btw awesome project!

**Comment by kreuzerk** [comment]
Hi @TitoMoi 

Thx a lot for reporting this issue. You were absolutely right, the default options were not correctly detected when provided over a config object. With this fix you should be able to remove the `generateType: true` from your `svg-to-ts` config.

It should now behave in the same way as the command line interface.
