### ISSUE TITLE
Allowing multiple sets of configurations in the package.json

### ISSUE THREAD

**Issue by yagoferrer** [kreuzerk/svg-to-ts#56]
Hi @kreuzerk,
I pulled the latest version of svg-to-ts, and unfortunately, I can't use it with the new configuration file. If the docs are up to date, you can only have: **one** set of source files and **one** output directory. I have a big project, and for performance reasons, I need to generate six files at various locations in my project.

I was wondering if the `svg-to-ts` entry, in the `package.json` you could also allow an set of configurations, not just only one.

It is possible to achieve that using command line (multiple times with different parameters) but it would be nice if I can have everything within the same configuration file. 

Congratulations on your project, this is a fantastic tool. 
Thank you!

**Comment by kreuzerk** [comment]
Hi @yagoferrer 

Thanks for reporting this feature request. We already once thought about supporting multiple configurations. So it is possible. May I ask what doesn't work for you when using a configuration file?

**Comment by yagoferrer** [comment]
Oh! Excelent, I'll give it a try then. It's just the documentation then, that needs to be updated to reflect that it is possible to pass multiple configurations.

**Comment by yagoferrer** [comment]
@kreuzerk,
This is what I'm trying to do and it does not work. In the package.json I added
```
"svg-to-ts": [
    {
      "conversionType": "object",
      "interfaceName": "CompanyIcon",
      "srcFiles": [
        "./icons/admin/company/**/*.svg"
      ],
      "outputDirectory": "./src/app/admin/company",
      "compileSources": true
    },
    {
      "conversionType": "object",
      "interfaceName": "TechnicianIcon",
      "srcFiles": [
        "./icons/admin/technician/**/*.svg"
      ],
      "outputDirectory": "./src/app/admin/technician",
      "compileSources": true
    }
  ]
```

**Comment by kreuzerk** [comment]
@yagoferrer now it's clear. Thx for the explanation

**Comment by KingDarBoja** [comment]
Also, should it be possible to add a shared interface for both configuration where `TechnicianIcon` and `CompanyIcon` can extend from? Something like `sharedModelName: BaseIcon` ?

**Comment by kreuzerk** [comment]
In the upcoming version `5.4.0` `svg-to-ts` can handle multiple configurations like this:

````json
[
  {
    "conversionType": "files",
    "srcFiles": [
      "./svg-icons/one/**/*.svg"
    ],
    "outputDirectory": "./dist/one",
    "interfaceName": "MyIconOne",
    "typeName": "myIconOne",
    "prefix": "myIconOne",
    "exportCompleteIconSet": true,
    "optimizeForLazyLoading": true,
    "modelFileName": "my-icon-one.model",
    "compileSources": true
  },
  {
    "conversionType": "files",
    "srcFiles": [
      "./svg-icons/two/**/*.svg"
    ],
    "outputDirectory": "./dist/two",
    "interfaceName": "MyIconTwo",
    "typeName": "myIconTwo",
    "prefix": "myIconTwo",
    "exportCompleteIconSet": true,
    "optimizeForLazyLoading": true,
    "modelFileName": "my-icon-two.model",
    "compileSources": true
  }
]
````
