### ISSUE TITLE
Error when having a folder in source dir

### ISSUE THREAD

**Issue by Palapapaa** [kreuzerk/svg-to-ts#6]
Hello,

Thank you for your lib, it does exactly what I need for my project.

However I had an error when having a folder in source dir.

I've made a pull request that fix that. #5

**Comment by kreuzerk** [comment]
Hello

Awesome! Thanks a lot!
The PR looks good. But there’s a conflict.

After the conflict is resolved, I will merge it.

Kind regards
Kevin

**Comment by Palapapaa** [comment]
Okay, will do :)

I have another suggestion.
In my icon folder I have subfolder that also contains icons (this is why I had my error).
Would you think it would be an interesting feature (or maybe it already exists) to include multiple source dir ? Another solution would be a include pattern like `./inputfiles/**` (but it seems more difficult to implement to me).

If you're interessed I can create a PR for this feature.

**Comment by kreuzerk** [comment]
Hi Guillaume

Thanks a lot. Yeah I think this is a great idea. 👍
A PR is more than welcome. Thanks for the contribution. That’s awesome!

Also if you have other ideas or further improvements, its welcome. 
Can I ask you if you use this project for an Icon library?

Kind regards

**Comment by kreuzerk** [comment]
I also added you as a collaborator - so you can directly push to this repository

**Comment by Palapapaa** [comment]
Yup, I'm currently working on an Angular component lib.
I have to make an Icon component, and was about to develop nearly the same tool to convert my SVG assets to TypeScript file.
Your lib was clean and easy to understand so I've decide it was a good idea to use it and modify it in order to fit my needs.

Thank you for adding me to contributors.

How do you want me to contribute ?
Do you want me to develop feature on a new branch ?

**Comment by kreuzerk** [comment]
Yes - that would be the best. Just a branch and a PR. That would be awesome!

**Comment by kreuzerk** [comment]
And use conventional commit messages - The release is fully automated. So once we merge to master new versions get released based on commit messages.

**Comment by kreuzerk** [comment]
Thx a lot @Palapapaa for your contributions.
