### ISSUE TITLE
Feature request/question: Convert SVGs to <symbol>s

### ISSUE THREAD

**Issue by Spielboerg** [kreuzerk/svg-to-ts#87]
I have been looking for a good solution for icon handling for a long time. In the meantime I wrote my own script to group all my icons in one file and convert each one to a `<symbol>` for easy referencing:

SVG sprite:
```html
<svg width="0" height="0">
  <symbol xmlns="http://www.w3.org/2000/svg" viewbox="0 0 32 32" id="some-icon-name"><path d="..." fill-rule="nonzero"/></symbol>
  <symbol ...></symbol>
</svg>
```
Usage:
```html
<svg>
  <use xlink:href="#some-icon-name"></use>
</svg>
```

But I did not implement tree-shaking, so your tool seems very promising to me.

So I have one suggestion & one question:
1. Could you provide an option to convert the SVGs to symbols (each one in a separate file) so that I can add each one to the DOM when a symbol is used for the first time? Any other icon instance can then use the icon reference.
2. I don't know if having multiple symbol files is useful for performance/optimization. Maybe you can give an assessment there?

**Comment by kreuzerk** [comment]
Hi @Spielboerg thanks a lot for this question and sorry for the late response.

1. It's a valid suggestion. However, this project aims to convert `SVG` files to `TypeScript`. Converting `SVG` icons to and `SVG` sprite with symbols in my opinion isn't a use case of this repository.

2. Don't know about symbols but having each Icon in a single file is very useful to improve bundle size. But usually, you need to implement an additional concept like an icon registry around. With such an approach a static code analyzer is able to analyze which icons are used and which not. Therefore he can effectively tree shake unused icons. In Angular for example, not only tree shaking can be achieved but also splitting. Means icons can even be split into lazy-loaded feature modules. 

I tried to summarize this in the following Blogpost that might be helpful: https://medium.com/angular-in-depth/how-to-create-a-fully-tree-shakable-icon-library-in-angular-c5488cf9cd76

If you try such an approach you still need to be careful that icons are not part of `ng-packagr`. Otherwhise they will end up in the main chunk. However, if you want to provide a really treeshakable library I recommend you to checkout this starter project that allready has `svg-to-ts` preconfigured. https://github.com/kreuzerk/svg-icon-library-starter

**Comment by kreuzerk** [comment]
@Spielboerg I close this ticket since there's nothing to implement in `svg-to-ts`. But let me know if you need any help.

**Comment by Spielboerg** [comment]
Hi @kreuzerk, thank you for your detailed answer.

1. I think I could solve this problem by creating the `<symbol>`s before converting them to TypeScript files, right?

2. Your blogpost helps me a lot to understand the main concept with the icon registry.
Maybe I misunderstood it, but if I import the same icon in two different modules (because I need the icon in two pages of different modules), both modules/bundles get larger, right? Or does the Angular Compiler automatically include the icon in a hierarchically higher module in such a case?

**Comment by kreuzerk** [comment]
Hi @Spielboerg 

Sorry for the late response.

1. Yes I think so.
2. If the icon is used in multiple lazy loaded modules it ends up in a shared chunk (at least in Angular)
